env:
  global:
    - PACKAGE="Wrap Plus"
    - SUBLIME_TEXT_VERSION="3"

os:
  - linux
  - osx

before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
  # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi

install:
  # Install Sublime and Sublime Unittesting.
  - sh travis.sh bootstrap

script:
  - sh travis.sh run_tests
