environment:
  global:
    PACKAGE: "Wrap Plus"
    SUBLIME_TEXT_VERSION: "3"

install:
  - ps: appveyor DownloadFile "https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/appveyor.ps1"
  # Install Sublime and Sublime Unittesting.
  - ps: .\appveyor.ps1 "bootstrap" -verbose

build: off

test_script:
  - ps: .\appveyor.ps1 "run_tests" -verbose
